name: "Pixi-Pack Install Script"
description: "Create an install script for a pixi-packed environment"
author: "Wytamma"
branding:
  icon: 'book'
  color: 'green'

inputs:
  entrypoint:
    description: "The entrypoint for the install script. The is the program to extract from the environment"
    required: false
  installScriptName:
    description: "Name of the install script"
    required: false
    default: 'install'

runs:
  using: "composite"
  steps:
    - name: Create Unix install script
      run: |
        mv ${{ github.action_path }}/install.template.sh ${{ inputs.installScriptName }}.sh
        sed -i "s|{{GH_USER}}|${{github.repository_owner}}|g" ${{ inputs.installScriptName }}.sh
        sed -i "s|{{PROJECT}}|${{ github.event.repository.name }}|g" ${{ inputs.installScriptName }}.sh
        sed -i "s|{{ENTRYPOINT}}|${{ inputs.entrypoint }}|g" ${{ inputs.installScriptName }}.sh
      shell: bash
