name: "Testing Pixi-Pack Action"

on:
  push:
    tags:
      - "v*.*.*"  # e.g., "v1.0.0"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # 1) Run your composite action for each matrix entry
      - name: Build install script
        uses: ./
      
      - name: Run install script
        run: |
          chmod +x install.sh
          ./install.sh
        shell: bash
